
// Sample doctor data
export const additionalDoctors = [
  {
    id: 16,
    name: 'Dr. Rajesh Sharma',
    specialty: 'Neurologist',
    experience: '14 years',
    location: 'AIIMS Brain Center, Bangalore',
    rating: 4.7,
    reviews: 118,
    fee: '₹1200',
    availableToday: true,
    image: 'https://img.freepik.com/premium-vector/doctor-character-design_8163-412.jpg',
    coordinates: { lat: 12.9716, lng: 77.5946 } // Bangalore
  },
  {
    id: 17,
    name: 'Dr. Priya Patel',
    specialty: 'Dermatologist',
    experience: '9 years',
    location: 'Skin Health Clinic, Chennai',
    rating: 4.5,
    reviews: 92,
    fee: '₹1000',
    availableToday: false,
    image: 'https://img.freepik.com/premium-vector/female-doctor-cartoon-character_24908-61247.jpg',
    coordinates: { lat: 13.0827, lng: 80.2707 } // Chennai
  },
  {
    id: 18,
    name: 'Dr. Anil Kapoor',
    specialty: 'Cardiologist',
    experience: '22 years',
    location: 'Heart & Vascular Institute, Hyderabad',
    rating: 4.9,
    reviews: 231,
    fee: '₹1500',
    availableToday: true,
    image: 'https://img.freepik.com/premium-vector/cartoon-doctor-holding-clipboard_29190-4754.jpg',
    coordinates: { lat: 17.3850, lng: 78.4867 } // Hyderabad
  },
  {
    id: 19,
    name: 'Dr. Meena Gupta',
    specialty: 'Psychiatrist',
    experience: '11 years',
    location: 'Mental Wellness Center, Kolkata',
    rating: 4.8,
    reviews: 104,
    fee: '₹1200',
    availableToday: false,
    image: 'https://img.freepik.com/premium-vector/female-doctor-with-stethoscope-cartoon-character_24908-61230.jpg',
    coordinates: { lat: 22.5726, lng: 88.3639 } // Kolkata
  },
  {
    id: 20,
    name: 'Dr. Vikram Singh',
    specialty: 'Orthopedic',
    experience: '17 years',
    location: 'Sports Medicine & Orthopedics, Pune',
    rating: 4.7,
    reviews: 138,
    fee: '₹1300',
    availableToday: true,
    image: 'https://img.freepik.com/premium-vector/cartoon-doctor-with-glasses-stethoscope_29190-5238.jpg',
    coordinates: { lat: 18.5204, lng: 73.8567 } // Pune
  },
  {
    id: 21,
    name: 'Dr. Anjali Desai',
    specialty: 'Endocrinologist',
    experience: '13 years',
    location: 'Diabetes & Hormone Center, Ahmedabad',
    rating: 4.6,
    reviews: 87,
    fee: '₹1100',
    availableToday: true,
    image: 'https://img.freepik.com/premium-vector/female-doctor-cartoon-illustration_24908-54662.jpg',
    coordinates: { lat: 23.0225, lng: 72.5714 } // Ahmedabad
  },
  {
    id: 22,
    name: 'Dr. Suresh Kumar',
    specialty: 'Ophthalmologist',
    experience: '19 years',
    location: 'Vision Care Institute, Jaipur',
    rating: 4.9,
    reviews: 189,
    fee: '₹1000',
    availableToday: false,
    image: 'https://img.freepik.com/premium-vector/doctor-cartoon-character-medical-staff_24640-65186.jpg',
    coordinates: { lat: 26.9124, lng: 75.7873 } // Jaipur
  },
  {
    id: 23,
    name: 'Dr. Nandini Reddy',
    specialty: 'Pediatrician',
    experience: '12 years',
    location: "Children's Health Center, Lucknow",
    rating: 4.8,
    reviews: 152,
    fee: '₹900',
    availableToday: true,
    image: 'https://img.freepik.com/premium-vector/female-doctor-cartoon-character-hospital-staff_24908-33544.jpg',
    coordinates: { lat: 26.8467, lng: 80.9462 } // Lucknow
  },
  {
    id: 24,
    name: 'Dr. Arjun Khanna',
    specialty: 'Allergist',
    experience: '8 years',
    location: 'Allergy & Asthma Specialists, Bhopal',
    rating: 4.5,
    reviews: 76,
    fee: '₹950',
    availableToday: false,
    image: 'https://img.freepik.com/premium-vector/smiling-young-male-doctor-holding-clipboard-cartoon-character_40876-1839.jpg',
    coordinates: { lat: 23.2599, lng: 77.4126 } // Bhopal
  },
  {
    id: 25,
    name: 'Dr. Sunita Verma',
    specialty: 'Rheumatologist',
    experience: '16 years',
    location: 'Arthritis Treatment Center, Chandigarh',
    rating: 4.7,
    reviews: 124,
    fee: '₹1100',
    availableToday: true,
    image: 'https://img.freepik.com/premium-vector/cute-female-doctor-character-with-clipboard-cartoon-vector-illustration_40876-3129.jpg',
    coordinates: { lat: 30.7333, lng: 76.7794 } // Chandigarh
  }
];
